"""使用 yt-dlp 解析并下载视频（支持 B 站、抖音等多平台）。"""
from pathlib import Path
from typing import Any, Optional

import yt_dlp

from src.common.config import load_config, get_download_dir


def _is_douyin(url: str) -> bool:
    u = (url or "").lower()
    return ("douyin.com" in u) or ("iesdouyin.com" in u)


def _get_douyin_cookie() -> str:
    """
    抖音解析需要较“新鲜”的 Cookie（不一定要登录）。
    该值建议由卖家工作台页面配置并保存到 config/config.yaml 的 download.douyin_cookie。
    """
    ck = (load_config().get("download", {}) or {}).get("douyin_cookie", "")
    if not ck:
        return ""
    # 允许在 YAML 里换行粘贴 cookie：这里统一压缩为空格，避免请求头里出现换行导致失败
    ck = " ".join(str(ck).split())
    return ck.strip()


def _get_douyin_cookies_from_browser() -> str:
    """
    可选：直接从本机浏览器读取 cookies（更“新鲜”，更适配抖音频繁变动的风控）。
    配置项：download.douyin_cookies_from_browser: chrome|edge|firefox|brave|opera
    返回浏览器名；为空表示不启用。
    """
    cfg = load_config().get("download", {}) or {}
    v = (cfg.get("douyin_cookies_from_browser") or "").strip().lower()
    if v in {"chrome", "edge", "firefox", "brave", "opera"}:
        return v
    return ""


def _ensure_douyin_cookiefile(cookie: str) -> str:
    """
    将 Cookie 字符串写入 Netscape cookiefile，供 yt-dlp 以 cookiejar 方式加载。
    仅设置 http_headers 在部分请求/重定向链路里可能不生效，cookiefile 更稳。
    返回 cookiefile 路径（字符串）。
    """
    base_dir = Path(get_download_dir())
    cookie_dir = base_dir / ".cache"
    cookie_dir.mkdir(parents=True, exist_ok=True)
    cookie_path = cookie_dir / "douyin.cookies.txt"

    # 解析 name=value; name2=value2 ...
    pairs: list[tuple[str, str]] = []
    for part in (cookie or "").split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, value = part.split("=", 1)
        name = name.strip()
        value = value.strip().replace("\t", " ")
        if name:
            pairs.append((name, value))

    # 写入 Netscape cookiefile（两域名都写一份，提升命中率）
    header = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by auto_download.",
        "",
    ]
    lines: list[str] = []
    for domain in (".douyin.com", ".iesdouyin.com"):
        for name, value in pairs:
            # domain, includeSubdomains, path, secure, expiry, name, value
            lines.append(f"{domain}\tTRUE\t/\tFALSE\t0\t{name}\t{value}")

    cookie_path.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    return str(cookie_path)


def get_video_info(video_url: str) -> dict[str, Any]:
    """
    仅拉取视频元数据（不下载），用于报价。
    返回: { "duration": 秒数, "height": 分辨率高度(px), "title": 标题, "ok": True } 或 { "ok": False, "error": "..." }
    """
    cfg = load_config().get("download", {})
    info_timeout = int(cfg.get("info_timeout_seconds", 15))
    ydl_opts = {
        "noplaylist": True,
        "quiet": True,
        "no_warnings": True,
        "extract_flat": False,
        # 避免解析卡死太久（手机端/短链/部分站点可能超时）
        "socket_timeout": info_timeout,
        "retries": 1,
    }
    if _is_douyin(video_url):
        browser = _get_douyin_cookies_from_browser()
        ck = _get_douyin_cookie()
        # 若配置了从浏览器读取，则始终优先使用浏览器 cookies（你在 Edge/Chrome 中登录抖音即可）
        if browser:
            ydl_opts["cookiesfrombrowser"] = (browser,)
        elif ck:
            ydl_opts["cookiefile"] = _ensure_douyin_cookiefile(ck)
            ydl_opts["http_headers"] = {
                "Cookie": ck,
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "Referer": "https://www.douyin.com/",
            }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=False)
        if not info:
            return {"ok": False, "error": "无法解析该链接"}
        duration = info.get("duration") or 0
        height = 0
        for f in (info.get("formats") or []):
            h = f.get("height") or 0
            if isinstance(h, int) and h > height:
                height = h
        return {
            "ok": True,
            "duration": int(duration) if duration else 0,
            "height": height,
            "title": (info.get("title") or "").strip() or "未命名视频",
        }
    except Exception as e:
        return {"ok": False, "error": str(e)}


def download_video(
    video_url: str,
    output_dir: Optional[str] = None,
    out_filename: Optional[str] = None,
    prefer_small_format: bool = False,
    max_duration_seconds: Optional[int] = None,
    batch_index: Optional[int] = None,
) -> Path:
    """
    下载视频到本地，返回下载好的文件路径。
    batch_index: 批量下载时传入序号（从 1 起），用于生成唯一文件名，避免同目录下多条链接因标题相同而互相覆盖。
    """
    cfg = load_config().get("download", {})
    base_dir = output_dir or get_download_dir()
    Path(base_dir).mkdir(parents=True, exist_ok=True)

    if out_filename:
        outtmpl = str(Path(base_dir) / out_filename)
    else:
        suffix = f"_{batch_index}" if batch_index is not None else ""
        if max_duration_seconds:
            base_name = f"%(title).80s{suffix}_partial_{max_duration_seconds}s.%(ext)s"
        else:
            base_name = f"%(title).80s{suffix}.%(ext)s"
        outtmpl = str(Path(base_dir) / base_name)

    format_str = cfg.get("format", "bestvideo+bestaudio/best")
    if prefer_small_format:
        format_str = cfg.get("format_small") or "bestvideo[height<=480]+bestaudio/best"

    ydl_opts = {
        "format": format_str,
        "outtmpl": outtmpl,
        "noplaylist": True,
        "merge_output_format": cfg.get("merge_format", "mp4"),
        "quiet": False,
        "no_warnings": True,
    }
    if _is_douyin(video_url):
        browser = _get_douyin_cookies_from_browser()
        ck = _get_douyin_cookie()
        if browser:
            ydl_opts["cookiesfrombrowser"] = (browser,)
        elif ck:
            ydl_opts["cookiefile"] = _ensure_douyin_cookiefile(ck)
            ydl_opts["http_headers"] = {
                "Cookie": ck,
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "Referer": "https://www.douyin.com/",
            }
    # 可选：按站点传入 extractor 参数（如 B 站等），详见 yt-dlp 文档
    extractor_args = cfg.get("extractor_args")
    if extractor_args and isinstance(extractor_args, dict):
        ydl_opts["extractor_args"] = extractor_args

    if max_duration_seconds is not None and max_duration_seconds > 0:
        end = max_duration_seconds
        ydl_opts["download_ranges"] = lambda *_: [{"start_time": 0, "end_time": end}]
    base_path = Path(base_dir)
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])

    # 下载/合并后找最新生成的视频文件
    video_exts = (".mp4", ".mkv", ".webm", ".flv", ".avi")
    candidates = [
        p for p in base_path.iterdir()
        if p.is_file() and p.suffix.lower() in video_exts and ".part" not in p.name
    ]
    if not candidates:
        raise FileNotFoundError(f"下载后未在 {base_dir} 找到视频文件")
    return max(candidates, key=lambda p: p.stat().st_mtime)
